
/*------------------------------------------------------------------------
    File        : CardCloseReason
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : vsink_000
    Created     : Wed May 12 17:59:43 EEST 2021
    Notes       : 
  ----------------------------------------------------------------------*/

enum wallester.api.CardCloseReason :  
    
    def enum
    ClosedByClient
    ClosedByIssuer
    ClosedBySystem.
    
end enum.