
/*------------------------------------------------------------------------
    File        : CardType
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : vsink_000
    Created     : Thu May 20 11:12:43 EEST 2021
    Notes       : 
  ----------------------------------------------------------------------*/

enum wallester.api.CardType :  
    def enum
    ChipAndPin 
    ChipAndPinAnonymous
    Virtual.

end enum.