
/*------------------------------------------------------------------------
    File        : DeliveryDispatchMethod
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : vsink_000
    Created     : Thu May 27 16:35:30 EEST 2021
    Notes       : 
  ----------------------------------------------------------------------*/

enum wallester.api.DeliveryDispatchMethod :  

    define enum
    StandardLatvianPostMail
    DPDExpress.

end enum.